use demoncoder::workflow::workspace::capture;
use std::os::unix::fs::MetadataExt;

#[test]
fn capture_retains_access_metadata_and_marks_historical_unknown() {
    let root = tempfile::tempdir().unwrap();
    std::fs::write(root.path().join("file"), b"original").unwrap();
    let snapshot = capture(root.path()).unwrap();
    let mut value = serde_json::to_value(&snapshot).unwrap();
    assert_eq!(value["metadata_version"], 1);
    let metadata = std::fs::metadata(root.path().join("file")).unwrap();
    let file = std::fs::File::open(root.path().join("file")).unwrap();
    let flags = rustix::fs::statx(
        &file,
        "",
        rustix::fs::AtFlags::EMPTY_PATH,
        rustix::fs::StatxFlags::BASIC_STATS,
    )
    .unwrap();
    assert_eq!(
        value["entries"]["./file"]["access"]["attributes"],
        flags.stx_attributes.bits()
    );
    assert_eq!(
        value["entries"]["./file"]["access"]["supported_attributes"],
        flags.stx_attributes_mask.bits()
    );
    assert_eq!(value["entries"]["./file"]["access"]["uid"], metadata.uid());
    assert_eq!(value["entries"]["./file"]["access"]["gid"], metadata.gid());
    assert_eq!(
        value["entries"]["./file"]["access"]["acl"]["Posix"]["access"],
        serde_json::Value::Null
    );
    value["entries"]["./file"]
        .as_object_mut()
        .unwrap()
        .remove("access");
    let old: demoncoder::workflow::workspace::Snapshot = serde_json::from_value(value).unwrap();
    assert!(!old.has_complete_access_metadata());
    assert!(demoncoder::workflow::workspace::review_evidence(&old, &snapshot).is_err());
    assert!(serde_json::to_value(old).unwrap()["entries"]["./file"]["access"].is_null());
}

use demoncoder::plugins::gate_snapshot::{GateReadSet, GateWorkspace};
use std::sync::atomic::AtomicBool;

#[test]
fn default_retains_dirty_and_untracked_bytes_without_output_exclusions() {
    let root = tempfile::tempdir().unwrap();
    let git = |args: &[&str]| {
        let output = std::process::Command::new("git")
            .arg("-C")
            .arg(root.path())
            .args(args)
            .env("GIT_CONFIG_GLOBAL", "/dev/null")
            .env("GIT_CONFIG_SYSTEM", "/dev/null")
            .output()
            .unwrap();
        assert!(output.status.success(), "git fixture failed");
        output.stdout
    };
    git(&["init", "--quiet"]);
    std::fs::write(root.path().join("tracked"), b"indexed original").unwrap();
    git(&["add", "tracked"]);
    std::fs::write(root.path().join("tracked"), b"dirty bytes").unwrap();
    assert_eq!(git(&["diff", "--name-only"]), b"tracked\n");
    std::fs::write(root.path().join("untracked"), b"untracked bytes").unwrap();
    std::fs::create_dir(root.path().join("target")).unwrap();
    std::fs::write(root.path().join("target/output"), b"generated bytes").unwrap();
    let workspace = GateWorkspace::open(root.path()).unwrap();
    let cancelled = AtomicBool::new(false);
    let snapshot = workspace
        .capture(&GateReadSet::default(), &cancelled)
        .unwrap();
    std::fs::write(root.path().join("tracked"), b"later").unwrap();
    assert_eq!(snapshot.entry("tracked").unwrap().bytes(), b"dirty bytes");
    assert_eq!(
        snapshot.entry("untracked").unwrap().bytes(),
        b"untracked bytes"
    );
    assert_eq!(
        snapshot.entry("target/output").unwrap().bytes(),
        b"generated bytes"
    );
    assert!(!workspace.is_current(&snapshot, &cancelled).unwrap());
    assert!(!format!("{snapshot:?}").contains("dirty bytes"));
}

#[test]
fn explicit_subset_and_no_match_glob_track_only_relevant_membership() {
    let root = tempfile::tempdir().unwrap();
    std::fs::create_dir(root.path().join("src")).unwrap();
    std::fs::write(root.path().join("src/a.rs"), b"a").unwrap();
    let workspace = GateWorkspace::open(root.path()).unwrap();
    let cancelled = AtomicBool::new(false);
    let selection = GateReadSet::new(
        vec!["src/a.rs".into()],
        vec!["src/*.toml".into()],
        vec!["missing/deep".into()],
    )
    .unwrap();
    let snapshot = workspace.capture(&selection, &cancelled).unwrap();
    assert_eq!(snapshot.absent_paths(), &["missing/deep"]);
    assert!(snapshot.glob_matches()["src/*.toml"].is_empty());
    std::fs::write(root.path().join("unrelated"), b"other").unwrap();
    std::fs::write(root.path().join("src/unrelated.txt"), b"other").unwrap();
    assert!(workspace.is_current(&snapshot, &cancelled).unwrap());
    std::fs::write(root.path().join("src/new.toml"), b"new").unwrap();
    assert!(!workspace.is_current(&snapshot, &cancelled).unwrap());
    std::fs::remove_file(root.path().join("src/new.toml")).unwrap();
    std::fs::create_dir(root.path().join("missing")).unwrap();
    assert!(!workspace.is_current(&snapshot, &cancelled).unwrap());
}

#[test]
fn default_acl_changes_revision_without_changing_directory_mode() {
    let root = tempfile::tempdir().unwrap();
    std::fs::create_dir(root.path().join("dir")).unwrap();
    let dir = std::fs::File::open(root.path().join("dir")).unwrap();
    let workspace = GateWorkspace::open(root.path()).unwrap();
    let flag = AtomicBool::new(false);
    let baseline = workspace.capture(&GateReadSet::default(), &flag).unwrap();
    let mode = dir.metadata().unwrap().mode();
    set_acl(&dir, "system.posix_acl_default", 4);
    let changed = workspace.capture(&GateReadSet::default(), &flag).unwrap();
    assert_eq!(mode, dir.metadata().unwrap().mode());
    assert_ne!(baseline.revision(), changed.revision());
    assert!(matches!(
        changed.entry("dir").unwrap().access().acl,
        demoncoder::plugins::gate_snapshot::AclMetadata::Posix {
            default: Some(_),
            ..
        }
    ));
    set_acl(&dir, "system.posix_acl_default", 0);
    assert!(!workspace.is_current(&changed, &flag).unwrap());
}

#[test]
fn access_acl_changes_revision_and_original_acl_is_retained() {
    use std::os::unix::fs::PermissionsExt;
    let root = tempfile::tempdir().unwrap();
    let path = root.path().join("file");
    std::fs::write(&path, b"bytes").unwrap();
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o640)).unwrap();
    let file = std::fs::File::open(&path).unwrap();
    let workspace = GateWorkspace::open(root.path()).unwrap();
    let flag = AtomicBool::new(false);
    let absent = workspace.capture(&GateReadSet::default(), &flag).unwrap();
    set_acl(&file, "system.posix_acl_access", 4);
    let first = workspace.capture(&GateReadSet::default(), &flag).unwrap();
    assert_eq!(
        absent.entry("file").unwrap().mode(),
        first.entry("file").unwrap().mode()
    );
    assert_ne!(absent.revision(), first.revision());
    let original = first.entry("file").unwrap().access().clone();
    set_acl(&file, "system.posix_acl_access", 0);
    assert!(!workspace.is_current(&first, &flag).unwrap());
    assert_eq!(&original, first.entry("file").unwrap().access());
    rustix::fs::fremovexattr(&file, "system.posix_acl_access").unwrap();
    assert!(workspace.is_current(&absent, &flag).unwrap());
}

fn set_acl(file: &std::fs::File, name: &str, permission: u16) {
    let mut acl = 2_u32.to_le_bytes().to_vec();
    for (tag, perm, id) in [
        (1_u16, 6_u16, u32::MAX),
        (2, permission, 65534),
        (4, 4, u32::MAX),
        (16, 4, u32::MAX),
        (32, 0, u32::MAX),
    ] {
        acl.extend(tag.to_le_bytes());
        acl.extend(perm.to_le_bytes());
        acl.extend(id.to_le_bytes());
    }
    rustix::fs::fsetxattr(file, name, &acl, rustix::fs::XattrFlags::empty()).unwrap();
}

#[test]
fn paths_are_validated_and_protected_content_cannot_be_explicitly_required() {
    for path in [
        "../escape",
        "/absolute",
        "a/../b",
        "a//b",
        "./a",
        ".ssh/key",
        ".env",
        ".git/HEAD",
        "a\\b",
    ] {
        assert!(
            GateReadSet::new(vec![path.into()], vec![], vec![]).is_err(),
            "{path}"
        );
        assert!(
            GateReadSet::new(vec![], vec![], vec![path.into()]).is_err(),
            "{path}"
        );
    }
    let root = tempfile::tempdir().unwrap();
    std::fs::write(root.path().join(".env"), b"private-canary").unwrap();
    std::fs::write(root.path().join("visible"), b"public").unwrap();
    let workspace = GateWorkspace::open(root.path()).unwrap();
    let flag = AtomicBool::new(false);
    let public = workspace.capture(&GateReadSet::default(), &flag).unwrap();
    assert!(public.entry(".env").is_none());
    assert!(!format!("{public:?}").contains("private-canary"));
    let required = GateReadSet::new(vec![], vec!["*".into()], vec![]).unwrap();
    let error = workspace.capture(&required, &flag).unwrap_err();
    assert!(!format!("{error:?}").contains(".env"));
}

#[test]
fn mode_kind_symlink_target_and_directory_membership_change_revision() {
    use std::os::unix::fs::{PermissionsExt, symlink};
    let root = tempfile::tempdir().unwrap();
    let outside = tempfile::tempdir().unwrap();
    let secret = outside.path().join("outside");
    std::fs::write(&secret, b"outside-canary").unwrap();
    let path = root.path().join("entry");
    std::fs::write(&path, b"inside").unwrap();
    let workspace = GateWorkspace::open(root.path()).unwrap();
    let flag = AtomicBool::new(false);
    let file = workspace.capture(&GateReadSet::default(), &flag).unwrap();
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o700)).unwrap();
    assert!(!workspace.is_current(&file, &flag).unwrap());
    std::fs::remove_file(&path).unwrap();
    symlink(&secret, &path).unwrap();
    let link = workspace.capture(&GateReadSet::default(), &flag).unwrap();
    assert_ne!(file.revision(), link.revision());
    assert_eq!(
        link.entry("entry").unwrap().bytes(),
        secret.as_os_str().as_encoded_bytes()
    );
    assert!(
        !link
            .entries()
            .any(|(_, entry)| entry.bytes() == b"outside-canary")
    );
    std::fs::remove_file(&path).unwrap();
    symlink("other-target", &path).unwrap();
    assert!(!workspace.is_current(&link, &flag).unwrap());
    std::fs::remove_file(&path).unwrap();
    std::fs::create_dir(&path).unwrap();
    let dir = workspace.capture(&GateReadSet::default(), &flag).unwrap();
    assert!(dir.memberships()["entry"].is_empty());
    std::fs::write(path.join("child"), b"child").unwrap();
    assert!(!workspace.is_current(&dir, &flag).unwrap());
}

#[test]
fn pinned_root_and_intermediate_links_cannot_redirect_capture() {
    use std::os::unix::fs::symlink;
    let parent = tempfile::tempdir().unwrap();
    let root = parent.path().join("root");
    std::fs::create_dir(&root).unwrap();
    std::fs::write(root.join("file"), b"inside").unwrap();
    let workspace = GateWorkspace::open(&root).unwrap();
    let flag = AtomicBool::new(false);
    let snapshot = workspace.capture(&GateReadSet::default(), &flag).unwrap();
    std::fs::rename(&root, parent.path().join("old")).unwrap();
    std::fs::create_dir(&root).unwrap();
    std::fs::write(root.join("file"), b"replacement").unwrap();
    assert!(workspace.is_current(&snapshot, &flag).is_err());
    let fresh = GateWorkspace::open(&root).unwrap();
    let outside = tempfile::tempdir().unwrap();
    std::fs::write(outside.path().join("private"), b"outside-canary").unwrap();
    symlink(outside.path(), root.join("link")).unwrap();
    for selection in [
        GateReadSet::new(vec![], vec!["link/*.rs".into()], vec![]).unwrap(),
        GateReadSet::new(vec!["link/private".into()], vec![], vec![]).unwrap(),
        GateReadSet::new(vec![], vec![], vec!["link/missing".into()]).unwrap(),
    ] {
        assert!(fresh.capture(&selection, &flag).is_err());
    }
}

#[test]
fn missing_required_present_absent_and_capture_limits_hold() {
    let root = tempfile::tempdir().unwrap();
    let workspace = GateWorkspace::open(root.path()).unwrap();
    let flag = AtomicBool::new(false);
    let required = GateReadSet::new(vec!["missing".into()], vec![], vec![]).unwrap();
    assert!(workspace.capture(&required, &flag).is_err());
    std::fs::write(root.path().join("file"), b"content").unwrap();
    let absent = GateReadSet::new(vec![], vec![], vec!["file".into()]).unwrap();
    assert!(workspace.capture(&absent, &flag).is_err());
    let file = std::fs::File::create(root.path().join("oversized")).unwrap();
    file.set_len(8 * 1024 * 1024 + 1).unwrap();
    assert!(workspace.capture(&GateReadSet::default(), &flag).is_err());
    let subset = GateReadSet::new(vec!["file".into()], vec![], vec![]).unwrap();
    assert!(workspace.capture(&subset, &flag).is_ok());
    flag.store(true, std::sync::atomic::Ordering::Relaxed);
    assert_eq!(
        workspace.capture(&subset, &flag).unwrap_err(),
        demoncoder::plugins::gate_snapshot::CaptureError::Cancelled
    );
}

#[test]
fn glob_matching_directory_is_membership_only_and_literal_directory_is_subtree() {
    let root = tempfile::tempdir().unwrap();
    std::fs::create_dir(root.path().join("dir")).unwrap();
    std::fs::write(root.path().join("dir/file"), b"initial").unwrap();
    let workspace = GateWorkspace::open(root.path()).unwrap();
    let flag = AtomicBool::new(false);
    let glob = GateReadSet::new(vec![], vec!["d*".into()], vec![]).unwrap();
    let initial = workspace.capture(&glob, &flag).unwrap();
    assert_eq!(initial.memberships()["dir"], ["file"]);
    assert!(initial.entry("dir/file").is_none());
    std::fs::write(root.path().join("dir/file"), b"later").unwrap();
    assert!(workspace.is_current(&initial, &flag).unwrap());
    std::fs::write(root.path().join("dir/new"), b"new").unwrap();
    assert!(!workspace.is_current(&initial, &flag).unwrap());
    let subtree = GateReadSet::new(vec!["dir".into()], vec![], vec![]).unwrap();
    assert_eq!(
        workspace
            .capture(&subtree, &flag)
            .unwrap()
            .entry("dir/file")
            .unwrap()
            .bytes(),
        b"later"
    );
}

#[test]
fn repeated_glob_evidence_has_an_aggregate_bound() {
    let root = tempfile::tempdir().unwrap();
    for index in 0..600 {
        std::fs::write(
            root.path().join(format!("{index:04}-{}", "x".repeat(120))),
            b"",
        )
        .unwrap();
    }
    let workspace = GateWorkspace::open(root.path()).unwrap();
    let globs = (0..128)
        .map(|index| format!("{{*,unused{index}}}"))
        .collect();
    let selection = GateReadSet::new(vec![], globs, vec![]).unwrap();
    assert!(
        workspace
            .capture(&selection, &AtomicBool::new(false))
            .is_err()
    );
    let bounded = GateReadSet::new(vec![], vec!["*".into()], vec![]).unwrap();
    assert!(workspace.capture(&bounded, &AtomicBool::new(false)).is_ok());
}

#[test]
fn retained_access_allocations_match_the_budgeted_material() {
    use demoncoder::plugins::gate_snapshot::AclMetadata;
    let root = tempfile::tempdir().unwrap();
    let directory = std::fs::File::open(root.path()).unwrap();
    set_acl(&directory, "system.posix_acl_default", 4);
    for index in 0..8 {
        let path = root.path().join(format!("file{index}"));
        std::fs::write(&path, b"content").unwrap();
        set_acl(
            &std::fs::File::open(path).unwrap(),
            "system.posix_acl_access",
            4,
        );
    }
    let workspace = GateWorkspace::open(root.path()).unwrap();
    let snapshot = workspace
        .capture(&GateReadSet::default(), &AtomicBool::new(false))
        .unwrap();
    let mut retained_bytes = 0;
    let mut allocated_bytes = 0;
    for (_, entry) in snapshot.entries() {
        let metadata = entry.access();
        if let AclMetadata::Posix { access, default } = &metadata.acl {
            for bytes in access.iter().chain(default.iter()) {
                assert_eq!(
                    bytes.len(),
                    44,
                    "fixture must retain actual POSIX ACL material"
                );
                retained_bytes += bytes.len();
                allocated_bytes += bytes.capacity();
            }
        }
        for (name, bytes) in &metadata.extended {
            retained_bytes += name.len() + bytes.len();
            allocated_bytes += name.capacity() + bytes.capacity();
        }
    }
    assert!(
        retained_bytes >= 9 * 44,
        "access and default ACLs must both be captured"
    );
    eprintln!(
        "captured access material: {retained_bytes} bytes; retained buffer capacity: {allocated_bytes} bytes"
    );
    assert_eq!(
        allocated_bytes, retained_bytes,
        "retained allocations must not multiply the metadata allowance"
    );
}
